Module8 task2
htmlacademy-php/576665-readme-12 pull request #15
Opened 2020-09-02 18:46 UTC by Nadiiya

2020-09-04 08:24 UTC, Shv-sergey70 requested changes

2020-09-04 08:24 UTC, Shv-sergey70 commented on profile.php
> +$posts = get_posts_by_parameters($link, ['user_id' => $profile_data['id']]);
Не хватает обязательного параметра `limit`. Код не работает

2020-09-04 08:24 UTC, Shv-sergey70 commented on profile.php
> +    exit ('PAGE NOT FOUND');
Можно этот текст не писать, чтобы отобразилась стандартная 404 страница

2020-09-04 08:24 UTC, Shv-sergey70 commented on profile.php
> +$profile_id = filter_input(INPUT_GET, 'user_id', FILTER_VALIDATE_INT);
Уже после этой строчки можно показывать 404, не выполняя запрос к БД. Следующая проверка как есть останется на 17 строке

2020-09-04 08:24 UTC, Shv-sergey70 commented on functions.php
> +    return false;
Используй тернарный оператор

2020-09-04 08:24 UTC, Shv-sergey70 commented on profile.php
> +        $profile_followers[$key]['is_current_user'] = ($current_user['id'] === $follower['id']) ? 'true' : 'false';
А зачем `true/false` хранить строкой?

2020-09-04 08:24 UTC, Shv-sergey70 commented on subscription.php
> +$author = get_user_data($link, (int) $author_id);
По сути тут тебе автор не нужен. Запрос внутри довольно сложный. Ты можешь написать функцию, которая будет выполнять запрос к БД и проверять, что запись с таким пользователем просто существует (такой запрос будет быстрее. Просто проверка по ID). 
`https://www.php.net/manual/ru/mysqli-result.num-rows.php`

2020-09-04 08:24 UTC, Shv-sergey70 commented on subscription.php
> +$path = $_SERVER['HTTP_REFERER'];
Можно без этой переменной сразу на 23 строке подставить значение

2020-09-04 08:24 UTC, Shv-sergey70 commented on templates/layout.php
> +                            <a class="header__profile-link" href="/profile.php?user_id=<?= $_SESSION['user']['id'] ? $_SESSION['user']['id'] : '' ?>">
В шаблонах лучше не использовать доступ к `$_SESSION` напрямую. Передавай нужные данные в шаблон снаружи

2020-09-04 08:24 UTC, Shv-sergey70 commented on templates/profile.php
> +                    <?php if ($profile_data['is_current_user'] !== 'true'): ?>
`true` как строка это не хорошо. Используй булев тип

2020-09-04 10:41 UTC, Nadiiya commented on profile.php
> +$profile_id = filter_input(INPUT_GET, 'user_id', FILTER_VALIDATE_INT);
Хочу уточнить, после 11 строчки редиректим на 404 если не получили данных из запроса, а тот, что на строке 17 сработает, если id получили, но в БД такого значения нет? Так?

2020-09-04 16:00 UTC, Nadiiya commented on subscription.php
> +$path = $_SERVER['HTTP_REFERER'];
Ок, еще хочу спросить, в мануале по этому заголовку сказано:

> 'HTTP_REFERER'
The address of the page (if any) which referred the user agent to the current page. This is set by the user agent. Not all user agents will set this, and some provide the ability to modify HTTP_REFERER as a feature. In short, it cannot really be trusted.

Not all user agents will set this - "запасной аэродром" не нужен?

2020-09-05 08:19 UTC, Shv-sergey70 commented on subscription.php
> +$path = $_SERVER['HTTP_REFERER'];
В целом можно. Но только если тебе хочется этим сейчас заниматься. Для учебного варианта текущее решение подойдет. Но можно так:
https://ru.stackoverflow.com/questions/582904/http-referer-%D1%81-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%BE%D0%BC-https-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D0%BB%D0%BA%D0%B0

2020-09-05 08:20 UTC, Shv-sergey70 commented on profile.php
> +$profile_id = filter_input(INPUT_GET, 'user_id', FILTER_VALIDATE_INT);
Да

2020-09-13 06:30 UTC, Shv-sergey70 commented on feed.php
> +check_page_access();
Если мы находимся на странице `feed`, то иконка должна подсвечиваться другая:
![image](https://user-images.githubusercontent.com/35741647/93011541-37177980-f5c1-11ea-8d60-b2bdc9ef6b58.png)

2020-09-13 06:30 UTC, Shv-sergey70 commented on feed.php
> +$post_types = get_post_types($link);
Это стоит делать сразу на 46 строчке, без сохранения в переменную. Вдруг у тебя запрос на 17 строчке упадет, и это действие, будет выполнено зря

2020-09-13 06:30 UTC, Shv-sergey70 commented on templates/feed.php
> +                    <?php foreach ($posts as $post): ?>
Надо показать вложенность `foreach` по отношению к `if`, добавив отступ

2020-09-13 06:30 UTC, Shv-sergey70 commented on profile.php
> +$profile_data['is_current_user'] = ($current_user['id'] === $profile_id) ? true : false;
Результат сравнения итак даст `true/false`, тернарный оператор не нужен

2020-09-13 06:35 UTC, merged